apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalable-app
  template:
    metadata:
      labels:
        app: scalable-app
    spec:
      containers:
      - name: scaletestapp
        image: shestera/scaletestapp:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "20Mi"
          limits:
            memory: "25Mi"