apiVersion: v1
kind: Service
metadata:
  name: scalable-app-service  # Имя сервиса
spec:
  selector:
    app: scalable-app  # Должно совпадать с метками (labels) из Deployment!
  ports:
    - port: 8080        # Порт, на котором сервис принимает запросы
  type: LoadBalancer     # Тип сервиса (ClusterIP, NodePort, LoadBalancer)